name: $(SourceBranchName)_$(Build.SourceVersion)

trigger:
 branches:
    include:
      - main
      - develop

pr: none

pool:
  vmImage: 'ubuntu-24.04'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: 'TemplateApi.sln'
    arguments: '--configuration Release'

- script: |
    aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNTID).dkr.ecr.$(AWS_REGION).amazonaws.com
  displayName: 'Login to Aws and ECR'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

- task: Bash@3
  displayName: Build app with Docker
  inputs:
      targetType: 'inline'
      script: |
        docker build -t $(DOCKER_REPOSITORYNAME) .

- task: Bash@3
  displayName: Push app container image to ECR
  inputs:
    targetType: 'inline'
    script: |
      echo "Git commit is $(Build.SourceVersion)"
      docker tag $(DOCKER_REPOSITORYNAME):latest $(AWS_ACCOUNTID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORYNAME):$(Build.SourceVersion)
      docker push $(AWS_ACCOUNTID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORYNAME):$(Build.SourceVersion)